### ISSUE TITLE
http://scriptlerweb.appspot.com/ is down

### ISSUE THREAD

**Issue by sschuberth** [jenkinsci/jenkins-scripts#30]
The [legacy script catalog](http://scriptlerweb.appspot.com/) is down. Please either bring it up again or adjust the [Wiki](https://wiki.jenkins-ci.org/display/JENKINS/Scriptler+Plugin) to not refer to it anymore.

**Comment by imod** [comment]
http://scriptlerweb.appspot.com is not supported anymore and removed from the plugin
